export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECT_PRODUCTS: "SELECTED_PRODUCTS",
    ADD_TO_CART: "ADD_TO_CART",  
    REMOVE_FROM_CART: "REMOVE_FROM_CART",  
    REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCTS",
};
